In [63]:
#importamos las librerias a usar

import requests
import pandas as pd
from datetime import datetime

In [2]:
#Extraemos la data desde el API haciendo uso de requests en formato json

API = "https://api.covidtracking.com/v1/us/daily.json"
response = requests.get(API).json()

In [67]:
# le damos el formato de dataframe a nuestro json con ayuda de pandas y guardamos esta data ordenada por la fecha

data = pd.json_normalize(response)

df = data.sort_values(by="date").reset_index(drop=True)

In [68]:
#modificamos las columnas que hacen referencia a una fecha y le damos el formato correspondiente

df['lastModified'] = df['lastModified'].str.replace('T24:00:00Z', 'T00:00:00Z')
df['lastModified'] = pd.to_datetime(df['lastModified'], format='%Y-%m-%dT%H:%M:%SZ').dt.date


df['dateChecked'] = df['dateChecked'].str.replace('T24:00:00Z', 'T00:00:00Z')
df['dateChecked'] = pd.to_datetime(df['dateChecked'], format='%Y-%m-%dT%H:%M:%SZ').dt.date


df['date'] = pd.to_datetime(df['date'], format='%Y%m%d')

In [84]:
#filtramos la data

df = df[df['positive'] > 0]

#Seleccionamos las columnas a usar

data_columns = ['date', 'positive', 'negative', 'pending',
       'hospitalizedCurrently', 'hospitalizedCumulative', 'inIcuCurrently',
       'inIcuCumulative', 'onVentilatorCurrently', 'onVentilatorCumulative',
       'dateChecked', 'death', 'hospitalized', 'totalTestResults',
       'lastModified', 'total', 'posNeg', 'deathIncrease',
       'hospitalizedIncrease', 'negativeIncrease', 'positiveIncrease',
       'totalTestResultsIncrease']

#generamos un id para nuestro dataframe
df = df[data_columns].reset_index(drop=True).reset_index()
df.rename(columns={'index': 'id'}, inplace=True)
df['id'] = df['id'] + 1

In [89]:
display(df)

,id,date,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,totalTestResults,lastModified,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,1,2020-01-19,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,2020-01-19,0,0,0,0,0,1,0
1,2,2020-01-20,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,2020-01-20,0,0,0,0,0,0,0
2,3,2020-01-21,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,2020-01-21,0,0,0,0,0,1,0
3,4,2020-01-22,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,2020-01-22,0,0,0,0,0,0,1
4,5,2020-01-23,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2,2020-01-23,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,410,2021-03-03,28520365.0,73857281.0,11778.0,45462.0,770821.0,9359.0,45214.0,3094.0,...,770821.0,357888671,2021-03-03,0,0,2449,2172,267001,66836,1406795
410,411,2021-03-04,28585852.0,74035238.0,12405.0,44172.0,772351.0,8970.0,45293.0,2973.0,...,772351.0,359479655,2021-03-04,0,0,1743,1530,177957,65487,1590984
411,412,2021-03-05,28654639.0,74307155.0,12213.0,42541.0,775132.0,8634.0,45373.0,2889.0,...,775132.0,361224072,2021-03-05,0,0,2221,2781,271917,68787,1744417
412,413,2021-03-06,28714654.0,74450990.0,11783.0,41401.0,775635.0,8409.0,45453.0,2811.0,...,775635.0,362655064,2021-03-06,0,0,1680,503,143835,60015,1430992
413,414,2021-03-07,28756489.0,74582825.0,11808.0,40199.0,776361.0,8134.0,45475.0,2802.0,...,776361.0,363825123,2021-03-07,0,0,842,726,131835,41835,1170059